version: '3.8'
volumes:
  migrations:

services:
  invio-api:
    # image: invio_image:latest
    container_name: app_server
    build: .
    command: yarn run start:dev
    ports:
      - 9009:5000
    env_file:
      - .env
    volumes:
      - ./.env:/home/app/.env
      - migrations:/home/app/prisma/migrations
    # network_mode: host
