version: '3.7'

services:
  app:
    container_name: inventory-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: 'postgres://ayindejohn:secret@postgres:5432/invio'

    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

    ports:
      # - '5432:5432'
      - '5434:5432'

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

    environment:
      REDIS_HOST: redis

    restart: unless-stopped

volumes:
  postgres:
    name: app
  redis:
    driver: local
