version: '3.7'

services:
  postgres:
    image: postgres:13-alpine

    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: 'secret'

      POSTGRES_USER: 'postgres'

      POSTGRES_DB: 'postgres'

    volumes:
      - ./.docker/volumes/pg_data:/var/lib/postgresql/data

    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine

    ports:
      - '6379:6379'

    restart: unless-stopped
